### ISSUE TITLE
Support more flexible version matching

### ISSUE THREAD

**Issue by willb** [fedora-java/xmvn#16]
This is a tricky problem.  We're interested in specifying ranges (or regexes, etc.) of versions for dependencies rather than simply supporting exact matches or allowing any version to match.

**Comment by mizdebsk** [comment]
I agree that XMvn should implement more sophisticated version matchers. This was on TODO list since very beginning of XMvn existence, but so far it hasn't been implemented mostly because there is no universal version scheme. For Maven version is just almost arbitrary string. It has limited support for version ranges, but they practically not used by the community.

Since there is no single way of comparing versions, I think that there should be more than one matcher available with a mechanism of specifying which one to use. For example, package providing compat version would specify which matcher to use.

Possible matchers:
- strict match; default for compat versions (unless package specifies to use a different one)
- version ranges; difficult to implement properly as they require ordering of versions
- regex; very powerful, but can be complex; Debian uses regexes
- number of matching components; simple, but would probably work in most of cases
- always match; could be used for default system versions (non-compat)

Maven has [code for version comparison](https://github.com/apache/maven-resolver/blob/3a1b8ae/maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersion.java#L94), but the code makes many assumptions about about how versions are constructed and therefore I'm not sure if it would work for us.

**Comment by mizdebsk** [comment]
Another thing to consider when implementing this is auto-requires/provides generation.

**Comment by mizdebsk** [comment]
This feature is very unlikely to be ever implemented, so I'm closing this ticket to keep focus on current issues. Feel free to reopen.
